### ISSUE TITLE
Any plans to support mapnik v3?

### ISSUE THREAD

**Issue by rnix** [fawick/go-mapnik#7]
./mapnik_c_api.cpp:2:10: fatal error: 'mapnik/graphics.hpp' file not found

Darn `brew upgrade ` and didn't notice it took mapnik 3.0.0. But if this can be updated easily to support 3.0, i'll hold-off on downgrading my mapnik.

Thanks

**Comment by springmeyer** [comment]
I presume it will be easy for @fawick to support Mapnik 3.0.0 once https://github.com/springmeyer/mapnik-c-api/issues/8 is solved, which I'll move on now.

**Comment by fawick** [comment]
Thanks for the heads-up, both of you, and thanks for the quick work on the C API @springmeyer! I wasn't tracking the mapnik development and would have missed the 3.0.0 release if it wasn't for you.

I will give it a look, however I am unsure how to test on Windows. Is there a pre-compiled 3.0.0 SDK for Windows available? I cannot built my own easily as I am bound to MSVC2010 at the moment and 3.0.0 requires MSVC2014, IIRC.

**Comment by springmeyer** [comment]
> Is there a pre-compiled 3.0.0 SDK for Windows available?

Yes:

 - 64 bit: https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-14.0-x64-v3.0.0.7z
 - 32 bit: https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-14.0-x86-v3.0.0.7z

Those include mapnik.dll and all deps built with Visual Studio 2014 CTP 4. In the next couple weeks (once MS releases 2015 officially) we will re-roll that against 2015. Tracking that at https://github.com/mapbox/windows-builds/issues/49

**Comment by fawick** [comment]
Great, thanks!

**Comment by fawick** [comment]
Still no luck on Windows w/ MSVC2010, as the 3.0.0 SDK headers, as C++11 Atomics are not supported by that compiler version, but are used in util/singleton.hpp.

@rnix But as now the links are fixed and springmeyer/mapnik-c-api#8 is closed, you should be good to go on Mac. Please give it a try and let me know.

**Comment by rnix** [comment]
:+1: I have verified that the library does indeed compile. I have not yet tested whether 3.0 _works_ :four_leaf_clover:

**Comment by fawick** [comment]
I'd be interested whether it works when you had the possibility to use it.

I wonder whether the issue should remain open until we know for sure that 3.0.0 is successfully supported by go-mapnik on Linux, Mac and Win...

**Comment by rnix** [comment]
I would say we can keep this closed. This was really just about the code compiling.
But, that said, I can use issue #6 too so i'll test that and this at the same time.
